name: Dynamics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070d09'
    - '#66b7a6'
    - '#326753'
    - '#ef723c'
  brandStrength: 0.7412876733578742
  lightness: 0.691176981665194
  saturation: 0.8119141650386155
  rhythmicContrast: 0.1310788025148213
purpose: []
